services:
  server:
    build:
      context: .
      target: server
    cap_drop:
      - ALL
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - ${COLNK_CONFIG_DIR:-.colnk-dev}/server.toml:/run/colnk/server.toml:ro
    ports:
      - "127.0.0.1:7443:7443/tcp"
    restart: unless-stopped
